manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com
    - name: urob
      url-base: https://github.com
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-nodefree-config
      remote: urob             # <--- This MUST match the remote name above
      revision: main
  self:
    path: config
